#include <iostream>
// Exemple sur les exceptions
// on inclut les exceptions standards que vous pouvez déclencher si-besoin
#include <stdexcept> // voir https://en.cppreference.com/w/cpp/header/stdexcept.html

// cette fonction va lancer des exceptions
void throw_exception(int i)
{
    if (i < 0)
    {
        // i chose a standard exception to throw:
        // domain_error, invalid_argument, length_error, out_of_range,
        // runtime_error, range_error, overflow_error, underflow_error
        // i generate a string with an error message
        // i throw an exception at random
        throw std::overflow_error(std::string("we throw an exception of type: overflow_error ") + std::to_string(i));
    }
    else if (i == 0)
    {
        throw std::invalid_argument(std::string("we throw an exception of type: invalid_argument ") + std::to_string(i));
    }
}

void exception_example(int i)
{
    // i enclose in a try bloc the code that can throw errors
    try
    {
        throw_exception(i);
    }
    // we catch the errors
    // C++ executes the first catch that matches the type of the exception
    catch (std::invalid_argument &e)
    {
        // do something to fix the problem
        // here we just print the message generated by the thrown exception
        std::cerr << e.what() << std::endl;
    }
    catch (std::overflow_error &e)
    {
        // do something to fix the problem
        // here we just print the message generated by the thrown exception
        std::cerr << e.what() << std::endl;
    }
}

int main()
{
    // run the exception example
    exception_example(-12);
    exception_example(0);
    return 0;
}
